name: theory8
favicon: null
layout_spectrum: 0.987939081620425
typography_spectrum: 0.0845506489276886
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.053423388628289104
  lightness: 0.046490906504914165
  saturation: 0.8941116670612246
  rhythmicContrast: 0.36485641286708415
purpose: []
